########## Get All Users
GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQDEyMyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzAxMDcyMDIwfQ.U287LYSAgwnxvtb9YuQZ9uA70tghWkZlk_YW-qAWsQI

########## Login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "Admin@123",
    "password": "123"
}


############ Register
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username":"Admin",
    "email": "AdminBoss@2s2f",
    "password": "123231"
}

#####

POST http://localhost:4000/auth/refreshToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQm9zc0AyczJmIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDEwNzMwNjMsImV4cCI6MTcwMTA4MDI2M30.U9LLh9NDO7i_47DpXZ5WX43MRJlBvaCmNYVrCKt_JtY

